[pytest]
addopts = --ignore doc
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
markers =
    only
    using_pytester
filterwarnings =
    ignore:The configuration option "asyncio_default_fixture_loop_scope" is unset:DeprecationWarning
